### ISSUE TITLE
Morning Session - Stand-Up Meeting - 21/4 

### ISSUE THREAD

**Issue by omar-labana** [Panda4cs/concept-lamo#1]

**Comment by IbrohimRasulov** [comment]
Great job, I like the discord bot. I have a question: do images have anything to tell about the image? I mean, when you want to get a random cat image, how the bot chooses the image that presents a cat?

**Comment by omar-labana** [comment]
@IbrohimRasulov You can just use !set <name of /r> and it will point the bot to this subreddit
